from dataclasses import dataclass, field
from typing import List

@dataclass
class Chapter:
    num: int
    title: str
    abstract: str
    subtopics: List[str]
    key_code: str          # the signature code this chapter teaches
    breakthrough: str      # the "aha" one-line framing

CHAPTERS: List[Chapter] = [
    Chapter(1, "The Deep Learning Revolution",
        "Why depth changed everything.",
        ["From symbolic AI to connectionism", "Why now: data + GPUs + optimization",
         "End-to-end learning"], "torch.nn.Linear",
        "Learning representations instead of engineering features."),
    Chapter(2, "The Mathematical Engine",
        "Backprop, gradients, and optimizers.",
        ["Computational graphs", "Chain rule & autograd", "SGD, momentum, Adam"],
        "torch.autograd", "The chain rule is the whole game."),
    Chapter(3, "Building Neurons",
        "MLPs, activations, training dynamics.",
        ["The perceptron to MLP", "ReLU/Sigmoid/GeLU", "Overfitting, regularization"],
        "nn.Sequential", "Non-linearity is what makes depth useful."),
    Chapter(4, "Convolutions & Computer Vision",
        "Exploiting spatial structure.",
        ["Conv/filter operations", "LeNet -> AlexNet", "Pooling & strides"],
        "nn.Conv2d", "Local + weight-sharing = learnable spatial priors."),
    Chapter(5, "The Depth Revolution",
        "How we learned to train very deep nets.",
        ["VGG", "Inception / multi-scale", "ResNet skip connections"],
        "nn.Residual", "Skip connections made 100+ layers trainable."),
    Chapter(6, "Seeing in Detail",
        "Detection and segmentation.",
        ["R-CNN family", "YOLO one-stage", "U-Net, Mask R-CNN"],
        "nn.FasterRCNN", "Turn a classifier into a pixel-level predictor."),
    Chapter(7, "Vision Transformers",
        "Attention meets pixels.",
        ["Patch embeddings", "ViT", "Swin, DINOv2 self-supervision"],
        "nn.MultiheadAttention", "Attention is a general-purpose compute layer."),
    Chapter(8, "Language Models & the NLP Turn",
        "Sequence models before the Transformer.",
        ["RNN/GRU/LSTM", "The vanishing gradient", "Seq2Seq + encoder-decoder"],
        "torch.nn.LSTM", "Context arrives as a walking recurrence."),
    Chapter(9, "Attention: The Breakthrough",
        "Attention is All You Need.",
        ["Scaled dot-product attention", "Multi-head", "Positional encoding"],
        "F.scaled_dot_product_attention", "Read any token directly from any other."),
    Chapter(10, "The Transformer Architecture",
        "Dissecting the machine.",
        ["Full encoder/decoder", "LayerNorm, residuals, FFN", "Parallelism at scale"],
        "nn.Transformer", "Scale + data + this block = emergent capability."),
    Chapter(11, "BERT: Understanding",
        "Bidirectional pretraining.",
        ["Masked LM", "Next sentence", "Fine-tuning paradigm"],
        "AutoModelForMaskedLM", "Pretrain, then adapt to a task with one head."),
    Chapter(12, "GPT: Generation",
        "Causal models that talk back.",
        ["Causal LM", "In-context learning", "Emergent abilities"],
        "AutoModelForCausalLM", "Predict the next token and everything else follows."),
    Chapter(13, "Scaling Laws & Emergence",
        "Predictable power.",
        ["Chinchilla scaling laws", "Emergence", "Data/compute trade-offs"],
        "training.loss", "Loss is a smooth function of scale."),
    Chapter(14, "Efficient Fine-Tuning",
        "One GPU, big models.",
        ["LoRA / QLoRA", "Prefix-tuning", "Quantization (MQQ, GPTQ)"],
        "peft.LoraConfig", "Train 1% of params for 99% of the gain."),
    Chapter(15, "Alignment",
        "Making models helpful and harmless.",
        ["Reward models", "RLHF / PPO", "DPO"],
        "reward_model.score", "Optimize for human preferences, not just likelihood."),
    Chapter(16, "Prompting, RAG & Agentic LLMs",
        "Extending models without training.",
        ["Prompt engineering", "Retrieval-augmented generation", "Tool calling"],
        "retriever.similar_docs", "Knowledge from retrieval, reasoning from prompts."),
    Chapter(17, "Multimodal & Generative Models",
        "Where vision and language meet.",
        ["CLIP alignment", "Diffusion models", "Vision-language models"],
        "CLIPModel", "Share one latent space across modalities."),
    Chapter(18, "LLM Agents & LangGraph",
        "Models that act.",
        ["Planning / reflection", "Tool use loops", "LangGraph state machines"],
        "StateGraph", "Agents are just control flow over an LLM."),
    Chapter(19, "Local Inference with Ollama & llama.cpp",
        "Run this whole stack yourself.",
        ["Quantization & GGUF", "GPU offloading", "Serving & prompt templates"],
        "llama_cpp.Llama", "Own the weights, own the privacy, own the cost."),
    Chapter(20, "Frontiers",
        "Beyond the Transformer.",
        ["State-space models (Mamba)", "Mixture of Experts", "Reasoning / world models"],
        "Mamba", "Linear-time attention alternatives are back."),
]